config/routes.rb
Rails.application.routes.draw do
  resources :user_forms
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :vaccinations
  root to: 'pages#home'

  get 'pages/user_list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form_image.rb
class FormImage < ApplicationRecord
  belongs_to :user_form

  mount_uploader :main_image, FormImageUploader
end

app/models/guest_user.rb
class GuestUser < User 
  attr_accessor :name, :first_name, :last_name, :email
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  has_many :user_forms, dependent: :delete_all

  def first_name
    self.name.split.first 
  end

  def last_name
    self.name.split.last 
  end
end

app/models/user_form.rb
class UserForm < ApplicationRecord
  belongs_to :user
  has_many :vaccs
  has_many :form_images

  accepts_nested_attributes_for :vaccs, 
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  accepts_nested_attributes_for :form_images,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['main_image'].blank? }


  
end

app/models/vacc.rb
class Vacc < ApplicationRecord
  belongs_to :user_form
  
  validates_presence_of :name

end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include CurrentUserConcern
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern 

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest User"
    guest.first_name = "Guest"
    guest.last_name = "User"
    guest.email = "guest@user.com"
    guest 
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern


  included do
    before_action :configure_permitted_parameters, if: :devise_controller?    
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def user_list
    @users = User.all 
  end
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  before_action :set_user_form, only: [:show, :edit, :update, :destroy]

  # GET /user_forms
  # GET /user_forms.json
  def index
    if current_user.role == :admin
      @user_forms = UserForm.all
    else
      @user_forms = UserForm.select { |uf| uf.user_id == current_user.id }
    end
  end

  # GET /user_forms/1
  # GET /user_forms/1.json
  def show
  end

  # GET /user_forms/new
  def new
    @user_form = UserForm.new
    1.times { @user_form.vaccs.build }
  end

  # GET /user_forms/1/edit
  def edit
  end

  # POST /user_forms
  # POST /user_forms.json
  def create
    @user_form = UserForm.new(user_form_params)
    @user_form.user_id = current_user.id

    respond_to do |format|
      if @user_form.save
        format.html { redirect_to @user_form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @user_form }
      else
        format.html { render :new }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_forms/1
  # PATCH/PUT /user_forms/1.json
  def update
    respond_to do |format|
      if @user_form.update(user_form_params)
        format.html { redirect_to @user_form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_form }
      else
        format.html { render :edit }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_forms/1
  # DELETE /user_forms/1.json
  def destroy
    @user_form.destroy
    respond_to do |format|
      format.html { redirect_to user_forms_url, notice: 'Form was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_form
      @user_form = UserForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_form_params
      params.require(:user_form).permit(:image, :user_id, vaccs_attributes: [:id, :name, :rec, :exp, :_destroy], form_images_attributes: [:id, :main_image, :_destroy])
    end
end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  before_action :set_vaccination, only: [:show, :edit, :update, :destroy]

  # GET /vaccinations
  # GET /vaccinations.json
  def index
    @vaccinations = Vaccination.all
  end

  # GET /vaccinations/1
  # GET /vaccinations/1.json
  def show
  end

  # GET /vaccinations/new
  def new
    @vaccination = Vaccination.new
  end

  # GET /vaccinations/1/edit
  def edit
  end

  # POST /vaccinations
  # POST /vaccinations.json
  def create
    @vaccination = Vaccination.new(vaccination_params)

    respond_to do |format|
      if @vaccination.save
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully created.' }
        format.json { render :show, status: :created, location: @vaccination }
      else
        format.html { render :new }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccinations/1
  # PATCH/PUT /vaccinations/1.json
  def update
    respond_to do |format|
      if @vaccination.update(vaccination_params)
        format.html { redirect_to @vaccination, notice: 'Vaccination was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccination }
      else
        format.html { render :edit }
        format.json { render json: @vaccination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccinations/1
  # DELETE /vaccinations/1.json
  def destroy
    @vaccination.destroy
    respond_to do |format|
      format.html { redirect_to vaccinations_url, notice: 'Vaccination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccination
      @vaccination = Vaccination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vaccination_params
      params.require(:vaccination).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
  
end

app/helpers/vaccinations_helper.rb
module VaccinationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A Great Company</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">

      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/pages/_unregistered.html.erb
<div class="text-center">
  <div class="top-marg-large">
    <h1>Welcome</h1>
    <h3>Please sign up or log in</h3>
    <p><small>login as admin to view all functionality</small></p>
    <p><small>Email: test@test.com  Password: hoagie573</small></p>
    <div class="top-marg-large bot-marg-large">
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-secondary btn-block btn-marg' %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-secondary btn-block btn-marg' %>
    </div>
  </div>
</div>

app/views/pages/_user_home.html.erb
<div class="text-center">
  <div class="top-marg-large">
    <h1>Welcome</h1>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="top-marg-large bot-marg-large">
        <div class="top-marg">
          <%= link_to "Create New Vaccination Form", new_user_form_path, class: 'btn btn-outline-secondary btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-5">
    <% if !current_user.is_a? GuestUser %>
      <%= render 'user_home' %>
    <% else %>
      <%= render 'unregistered' %>
    <% end %>
  </div>
  <div class="col-md-7">
    <div class="form-card">
      <%= image_tag "vacc_main.jpg", width: '100%' %>
    </div>
  </div>
</div>

app/views/pages/user_list.html.erb
<div class="top-marg-large"> 
  <h1>Users</h1>
  <hr />
</div>
<div class="row">
  <div class="col-md-8">
    <div class="card top-marg-large">
      <% @users.each do |user| %>
        <div class='form-card'>
          <div class="row">
            <div class="col-md-8">
              <h3 class="top-marg"><%= user.name %></h3>
              <p><small>Created <%= distance_of_time_in_words(user.created_at, Time.now) %> ago</small></p>
            </div>
            <div class="col-md-4">
              <%= link_to 'Delete User', root_path, class: 'btn btn-outline-danger' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Your Company Notification", sticky: false, image: :warning, :time => 2000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Your Company Notification", sticky: false, image: :error, :time => 2000) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Your Company Notification", sticky: false, image: :success, :time => 2000) %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top foot-pos">
  <div class="row">
    <div class="col-12 col-md">
      <%= image_tag 'company_logo.png', width: '75px', alt: 'your company logo', class: 'mb-2' %>
      <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal">A Great Company</h5>
  <%  if !current_user.is_a? GuestUser %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to 'Home', root_path, class: "p-2 text-dark" %>
      <%= link_to 'Forms', user_forms_path, class: "p-2 text-dark" %>
      
      <% if current_user.role == :admin %>
        <%= link_to 'User List', pages_user_list_path, class: "p-2 text-dark" %>
        <%= link_to 'Vaccinations', vaccinations_path, class: "p-2 text-dark" %>
      <% end %>
    </nav>
  
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
  <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to 'Home', root_path, class: "p-2 text-dark" %>
    </nav>
    <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-outline-primary" %> 
    <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/user_forms/_blank_vacc_fields.html.erb
<div class="form-group nested-fields">
  <div class='form-row'>
    <div class='col-md-4 mb-3'>
      <%= f.label :vaccination %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="col-md-4 mb-3">
      <%= f.label :received %>
      <%= f.date_field :rec, class: 'form-control' %>
    </div>
    <div class="col-md-4 mb-3">
      <%= f.label :expires %>
      <%= f.date_field :exp, class: 'form-control' %>
    </div>
    <%= link_to_remove_association 'Remove Vaccination', f, class: 'btn btn-outline-danger btn-sm' %>
  </div>
</div>

app/views/user_forms/_form.html.erb
<div class='row'>
  <div class="col-md-8">
    <%= form_with(model: user_form, local: true) do |f| %>
      <% if user_form.errors.any? %>
        <% user_form.errors.full_messages.each do |message| %>
          <%= js add_gritter(error, title: "Your Company App Notification", sticky: false, image: :notice) %>
        <% end %>
      <% end %>

      <div>
        <%= f.fields_for :vaccs do |v| %>
          <%= render 'vaccs_fields', f: v %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add From Selection', f, :vaccs, partial: 'vaccs_fields', class: 'btn btn-outline-info' %>
          <%= link_to_add_association 'Add Blank Field', f, :vaccs, partial: 'blank_vacc_fields', class: 'btn btn-outline-info' %>
        </div>
      </div>

      <div>
        <%= f.fields_for :form_images do |fi| %>
          <%= render 'image_fields', f: fi %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Image', f, :form_images, partial: 'image_fields', class: 'btn btn-outline-dark top-marg' %>
        </div>
      </div>
      <div class="top-marg-large">
        <div class="form-group">
          <%= f.submit 'Create Form', class: 'btn btn-outline-primary btn-block top-marg' %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <div class='card form-card'>
      <h4 class="top-marg">Notes:</h4>
      <div class="notes-list">
        <p>The following are included in the dropdown selection menu</p>
        <ul>
          <li>Tdap</li>
          <li>Tuberculosis</li>
          <li>Hep A</li>
          <li>Hep B</li>
          <li>Varicella</li>
          <li>Rubella</li>
          <li>Mumps</li>
          <li>Anti-hbs</li>
          <li>Rubeola</li>
        </ul>
        <p>If the selection menu does not include a needed option, open a blank item using the <u><i>Add Blank Field</i></u> button</p>

      </div>
    </div>
  </div>
</div>

app/views/user_forms/_image_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :image %>
  <%= f.file_field :main_image, id: :user_form_image, class: 'form-control' %>
  <div class="top-marg">
    <%= link_to_remove_association 'Remove Image', f, class: 'btn btn-outline-danger btn-sm' %>
  </div>
</div>

app/views/user_forms/_vaccs_fields.html.erb
<div class="form-group nested-fields">
  <div class="form-row">
    <div class='col-md-4 mb-3'>
      <%= f.label :vaccination %>
      <%= f.collection_select(:name, Vaccination.all, :title, :title, { :prompt => 'Select an option'}, { :multiple => false, class: 'form-control' }) %>
    </div>
    <div class='col-md-4 mb-3'>
      <%= f.label :received %>
      <%= f.date_field :rec, class: 'form-control' %>
    </div>
    <div class='col-md-4 mb-3'>
      <%= f.label :expires %>
      <%= f.date_field :exp, class: 'form-control' %>
    </div>
    <%= link_to_remove_association 'Remove Vaccination', f, class: 'btn btn-outline-danger btn-sm' %>
  </div>
</div>

app/views/user_forms/edit.html.erb
<h1>Edit Form</h1>

<div class="top-marg">
  <%= render 'form', user_form: @user_form %>
</div>

<div class="top-marg">
  <%= link_to 'Show', @user_form, class: 'btn' %> |
  <%= link_to 'Back', user_forms_path, class: 'btn' %> |
  <%= link_to 'Delete', @user_form, method: :delete, data: { confirm: 'Are your sure?' }, class: 'btn' %>
</div>

app/views/user_forms/index.html.erb
<h1 class="top-marg">Forms</h1>

<div class="top-marg">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Created</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user_forms.each do |user_form| %>
        <tr>
          <td><%= user_form.id %></td>
          <td><%= user_form.created_at %></td>
          <td><%= user_form.user.first_name %></td>
          <td><%= link_to '', user_form, class: 'fas fa-glasses fa-2x' %></td>
          <td><%= link_to '', edit_user_form_path(user_form), class: "far fa-edit" %></td>
          <td><%= link_to '', user_form, method: :delete, data: { confirm: 'Are you sure?' }, class: "fas fa-trash-alt" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<div class="top-marg-large">
  <%= link_to 'Create New Form', new_user_form_path, class: 'btn btn-light' %>
</div>

app/views/user_forms/new.html.erb
<h1>New User Form</h1>

<%= render 'form', user_form: @user_form %>

<div class="top-marg">
  <%= link_to 'Back', user_forms_path, class: 'btn' %>
</div>

app/views/user_forms/show.html.erb
<h2 class="top-marg"><%= @user_form.user.name %>:</h2>

<div class="top-marg">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Vaccination</th>
        <th>Date Received</th>
        <th>Expiration</th>
      </tr>
    </thead>
    <tbody>
      <% @user_form.vaccs.each do |v| %>
        <tr>
          <td><%= v.name %></td>
          <td><%= v.rec %></td>
          <td><%= v.exp %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="top-marg-large">
  <h4>Images:</h4>
  <div class="text-center">
    <% @user_form.form_images.each do |fi| %>
      <div class="top-marg">
        <%= image_tag fi.main_image %>
      </div>
    <% end %>
  </div>
</div>

<div class="top-marg">
  <%= link_to 'Edit', edit_user_form_path(@user_form), class: 'btn' %> |
  <%= link_to 'Back', user_forms_path, class: 'btn' %> |
  <%= link_to 'Delete', @user_form, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn' %>
</div>

app/views/vaccinations/_form.html.erb
<%= form_with(model: vaccination, local: true) do |form| %>
  <% if vaccination.errors.any? %>
    <% vaccination.errors.full_messages.each do |message| %>
      <%= js add_gritter(error, title: "Your Company App Notification", sticky: false, image: :notice) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :vaccination_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Vaccination', class: 'btn btn-primary top-marg' %>
  </div>
<% end %>

app/views/vaccinations/edit.html.erb
<div class="top-marg-large">
  <h1>Edit Vaccination</h1>

  <div class="row">
    <div class="col-md-8">
      <%= render 'form', vaccination: @vaccination %>
    </div>
  </div>
</div>

<div class="top-marg-large">
  <%= link_to 'Show', @vaccination, class: 'btn' %> |
  <%= link_to 'Back', vaccinations_path, class: 'btn' %>
</div>

app/views/vaccinations/index.html.erb
<h1>Vaccinations</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vaccinations.each do |vaccination| %>
      <tr>
        <td><%= vaccination.title %></td>
        <td><%= link_to 'Show', vaccination, class: 'btn' %></td>
        <td><%= link_to 'Edit', edit_vaccination_path(vaccination), class: 'btn' %></td>
        <td><%= link_to 'Destroy', vaccination, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vaccination', new_vaccination_path, class: 'btn btn-dark' %>

app/views/vaccinations/new.html.erb
<h1>New Vaccination</h1>

<div class="row">
  <div class="col-md-8 top-marg-large">
    <%= render 'form', vaccination: @vaccination %>
  </div>
</div>

<%= link_to 'Back', vaccinations_path, class: 'btn' %>

app/views/vaccinations/show.html.erb
<div class="text-center top-marg-large">
  <h2><%= @vaccination.title %></h2>
</div>

<div class="top-marg-large">
  <%= link_to 'Edit', edit_vaccination_path(@vaccination), class: 'btn btn-light' %> |
  <%= link_to 'Back', vaccinations_path, class: 'btn btn-light' %>
</div>